language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install .
script: pytest
deploy:
  provider: pypi
  username: __token__
  password:
    secure: FRHMfNFiaRt61c/LuqjtxZOjaKkCfOEjnc7WubZPA6OpNO9Ce4DvyaqRWfCiaJAj4/CmIF5IFEnAmvPlukrWnu3CP/x8wDj/hI75ILx6dESAwRM4u7Qahwv+cdzdLZfiCtIlSzXuCWHqiP+D5MrL4em241+HLGeZQPNcR84ZsqCNIBp/WuD8MAflaculf9twJ8bFUsJFGPF+TlYmK2KiNyeJxTM5JVYrcHQN+b75rY4NRTNwJ2vvuK2BevCDmEEI33Fn34SREd5aWZQjF39ZqKdEHZuvkTuF0tTlEPd+IvWZpjhvpxUoLMeU7xnVse2jZvbFdRSb0iwTNDWKM3j08qzB6nZd/gkJgYXbtUvScRvHSJkEwXP7sW391ZwtvFfWg3lU4j3ufUS1cKYsrQ04spcoMoI3vUOadNWBRtM6iHRyDeki/HiiTNbG1Qn3Os4w/94M/DpwC92V03gAgYn+WYRYePyVexBhrki10K1PdPfgbSmX8CjRlMe1Cevqm3yZd/j16f2jr/FtwsGNthWDOVNlktwcSISEBPOr569FYk6NGAFIZMkfL+0COF55d1C2JrD46pc1muGY9CtbGvAsgJvhBiJJWZkqsWIePlJtgbm4xSsWqmjNBS+DbIn2k3oBKYWfbi/t2KiEv3xpwkomvjucEGQg07UmpSk0UzxPmvY=
  on:
    branch: main
branches:
  only:
  - main
