language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install .
script: pytest
deploy:
  provider: pypi
  username: c00k1ez
  password:
    secure: qNqI1g1rUPKo29ticJs+li7Lw3UgvWmAkxGwm88qss25RwNc30T9DENx5e7oRtsjJzFtxr+ltgAUZNIvlTqozaikw8r+zr7Z0EatQGnqv6MKZcIRsSZ1fylo35aEulQkvnSXnCQLClUy/UcU5yI4ob1jAGKvWUOqcJitxcJZPKRx7gLzm0q7+jZuUcX3DRhwBVhR8xk6ef93hukN7p2/47fQ10XEA5EGpgAXZqQldkuwWI9gNGy5J5t6AbW7EGBpiUKPdrZGfg3pONPHRk629vBHoWZ+C3DnKkFxEhWfwWH37q4sPBXUVm67BYeopLqlZVKrBxjtF6ZzwIL6VhIVPwlrBm7SMZQf7a4yCz97YWicSG+v54co9HqbMPZbatGLVbIOxN1DecImyLVmB+4Xb6cxpTE+9hwZvdt0DKIRw/iqIgRU0kTuQLCYK7wWQhFXpUmjX/pCljt/i+UfZ/Wl+rzRYlq9ZDLYAViAkJ41bF29PYm5ORMltQ6vJmlOR2qljuNz8wiGMSEkuRd1InCLQzJliY5PPxOoGmczLKBxIJjOGkr8cZrmyoHSN/fohCe90ZT4Pvn6/Xe80Yg8ZfPLdTe7eCiZ820mmBMPRFOsbfTFWA6EEGG17xAh2hqaErPTbzmrXjRLZbrFvnAmaWCDaTBEm4W9iLXWHnjnOBEpH2w=
  on:
    branch: main
branches:
  only:
  - main
